// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unumpb/unumpb.proto

package unumpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3ae81cba83a78c, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PingResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3ae81cba83a78c, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendSMSRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSMSRequest) Reset()         { *m = SendSMSRequest{} }
func (m *SendSMSRequest) String() string { return proto.CompactTextString(m) }
func (*SendSMSRequest) ProtoMessage()    {}
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3ae81cba83a78c, []int{2}
}

func (m *SendSMSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSMSRequest.Unmarshal(m, b)
}
func (m *SendSMSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSMSRequest.Marshal(b, m, deterministic)
}
func (m *SendSMSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSMSRequest.Merge(m, src)
}
func (m *SendSMSRequest) XXX_Size() int {
	return xxx_messageInfo_SendSMSRequest.Size(m)
}
func (m *SendSMSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSMSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSMSRequest proto.InternalMessageInfo

func (m *SendSMSRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SendSMSResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSMSResponse) Reset()         { *m = SendSMSResponse{} }
func (m *SendSMSResponse) String() string { return proto.CompactTextString(m) }
func (*SendSMSResponse) ProtoMessage()    {}
func (*SendSMSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3ae81cba83a78c, []int{3}
}

func (m *SendSMSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSMSResponse.Unmarshal(m, b)
}
func (m *SendSMSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSMSResponse.Marshal(b, m, deterministic)
}
func (m *SendSMSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSMSResponse.Merge(m, src)
}
func (m *SendSMSResponse) XXX_Size() int {
	return xxx_messageInfo_SendSMSResponse.Size(m)
}
func (m *SendSMSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSMSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendSMSResponse proto.InternalMessageInfo

type SendSlackMessageRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSlackMessageRequest) Reset()         { *m = SendSlackMessageRequest{} }
func (m *SendSlackMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendSlackMessageRequest) ProtoMessage()    {}
func (*SendSlackMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3ae81cba83a78c, []int{4}
}

func (m *SendSlackMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSlackMessageRequest.Unmarshal(m, b)
}
func (m *SendSlackMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSlackMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendSlackMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSlackMessageRequest.Merge(m, src)
}
func (m *SendSlackMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendSlackMessageRequest.Size(m)
}
func (m *SendSlackMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSlackMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSlackMessageRequest proto.InternalMessageInfo

func (m *SendSlackMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendSlackMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSlackMessageResponse) Reset()         { *m = SendSlackMessageResponse{} }
func (m *SendSlackMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendSlackMessageResponse) ProtoMessage()    {}
func (*SendSlackMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3ae81cba83a78c, []int{5}
}

func (m *SendSlackMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSlackMessageResponse.Unmarshal(m, b)
}
func (m *SendSlackMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSlackMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendSlackMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSlackMessageResponse.Merge(m, src)
}
func (m *SendSlackMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendSlackMessageResponse.Size(m)
}
func (m *SendSlackMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSlackMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendSlackMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingRequest)(nil), "unumpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "unumpb.PingResponse")
	proto.RegisterType((*SendSMSRequest)(nil), "unumpb.SendSMSRequest")
	proto.RegisterType((*SendSMSResponse)(nil), "unumpb.SendSMSResponse")
	proto.RegisterType((*SendSlackMessageRequest)(nil), "unumpb.SendSlackMessageRequest")
	proto.RegisterType((*SendSlackMessageResponse)(nil), "unumpb.SendSlackMessageResponse")
}

func init() {
	proto.RegisterFile("unumpb/unumpb.proto", fileDescriptor_5a3ae81cba83a78c)
}

var fileDescriptor_5a3ae81cba83a78c = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xcd, 0x2b, 0xcd,
	0x2d, 0x48, 0xd2, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x22, 0x17, 0x77, 0x40, 0x66, 0x5e, 0x7a, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10,
	0x17, 0x4b, 0x49, 0x6a, 0x45, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4,
	0xc4, 0xc5, 0x03, 0x51, 0x52, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x8a, 0x55, 0x8d, 0x0a, 0x17, 0x5f,
	0x70, 0x6a, 0x5e, 0x4a, 0xb0, 0x6f, 0x30, 0x92, 0x49, 0x49, 0xf9, 0x29, 0x95, 0x30, 0x55, 0x20,
	0xb6, 0x92, 0x20, 0x17, 0x3f, 0x5c, 0x15, 0xc4, 0x30, 0x25, 0x5d, 0x2e, 0x71, 0xb0, 0x50, 0x4e,
	0x62, 0x72, 0xb6, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0x3e, 0xb7, 0x48, 0x71, 0x49, 0x60,
	0x2a, 0x87, 0x18, 0x65, 0x74, 0x86, 0x91, 0x8b, 0x25, 0x34, 0xaf, 0x34, 0x57, 0xc8, 0x90, 0x8b,
	0x05, 0xe4, 0x60, 0x21, 0x61, 0x3d, 0xa8, 0x97, 0x91, 0x7c, 0x28, 0x25, 0x82, 0x2a, 0x08, 0xf5,
	0x93, 0x15, 0x17, 0x3b, 0xd4, 0x65, 0x42, 0x62, 0x30, 0x05, 0xa8, 0x1e, 0x92, 0x12, 0xc7, 0x10,
	0x87, 0xea, 0x0d, 0xe5, 0x12, 0x40, 0x77, 0x93, 0x90, 0x3c, 0x8a, 0x62, 0x4c, 0xcf, 0x49, 0x29,
	0xe0, 0x56, 0x00, 0x31, 0xd6, 0x89, 0x23, 0x0a, 0x1a, 0x47, 0x49, 0x6c, 0xe0, 0x28, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xda, 0x88, 0x4e, 0x55, 0xc9, 0x01, 0x00, 0x00,
}
